MyProject/Models/Client.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string Summery { get; set; }
        public string Email { get; set; }
        public int PhoneNO { get; set; }
        public bool IsActive { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}

MyProject/Areas/Admin/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;

namespace MyProject.Areas.Admin.Controllers
{
    public class ClientsController : Controller
    {
        private JobStepEntities db = new JobStepEntities();

        // GET: Admin/Clients
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: Admin/Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Admin/Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "ClientID,Name,Summery,Email,PhoneNO,IsActive,image")] Client client, HttpPostedFileBase image)
        {
            string guid = Guid.NewGuid().ToString("N").ToLower();
            string Extenstion = image.FileName.Split('.')[1];
            if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
            {
                return View(client);
            }
            string filename = guid + '.' + Extenstion;
            image.SaveAs(Server.MapPath("~/Uploads/client/" + filename));
            client.image = filename;
            
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Admin/Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Admin/Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ClientID,Name,Summery,Email,PhoneNO,IsActive,image")] Client client, HttpPostedFileBase image)
        {
            if (image != null)
            {
                string guid = Guid.NewGuid().ToString("N").ToLower();
                string Extenstion = image.FileName.Split('.')[1];
                if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
                {
                    return View(client);
                }
                string filename = guid + '.' + Extenstion;
                image.SaveAs(Server.MapPath("~/Uploads/client/" + filename));
                //delete file from server
                string old_file_name = client.image;
                var uri = new Uri(Server.MapPath("~/Uploads/client/" + old_file_name));
                System.IO.File.Delete(uri.LocalPath);
                //add new file to database
                client.image = filename;
            }
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Admin/Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Admin/Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Client client = db.Clients.Find(id);
            Project ClientPr = db.Projects.Where(x => x.ClientID == id).FirstOrDefault();
            if (ClientPr != null)
            {
                ViewBag.error = " Sorry there is a Project  has  relation with this client you can't delet itو You must delete the associated Project first";


                return View(client);
            }
            else
            {
                //to catch the photo name
                var photoName = "";
                photoName = client.image;

                db.Clients.Remove(client);
                db.SaveChanges();
                //delet the photo

                string fullPath = Request.MapPath("~/Uploads/client/"
                + photoName);

                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);

                }
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Areas/Admin/Views/Clients/Create.cshtml
@model MyProject.Models.Client

@{
    ViewBag.Title = "Create";
}


<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-plus"></i>Add Client
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            @using (Html.BeginForm("Create", "Clients", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <h4>Client</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Summery, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Summery, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Summery, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNO, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNO, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNO, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="image" id="image" />

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/Clients/Delete.cshtml
@model MyProject.Models.Client

@{
    ViewBag.Title = "Delete";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">

<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trash"></i>  Delete
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            <h3>Are you sure you want to delete this?  </h3>
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Summery)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Summery)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNO)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNO)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/client/@Model.image" width="100" height="100" />
                    </dd>
                </dl>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <br />
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-sm red " type="submit">
                                <i class="fa fa-trash"></i>&nbsp; Delete
                            </button>
                            <a href="@Url.Action("Index")" class="btn btn-sm default">
                                <i class="fa fa-forward"></i> Back to List
                            </a>
                            <br />
                        </div>
                    </div>
                }
                <br />
            </div>
        </div>
    </div>
</div>


@section scriptFooter
{
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
  $( function() {
    $( "#dialog" ).dialog();
  } );
    </script>
}
@{
    string massg = "";
    if (ViewBag.error != null)
    { massg = ViewBag.error; }
    else
    { massg = " If there is any project has any relation with this Client you can't delet it"; }

}
<div id="dialog" title="Warning" class="danger">
    <p>@massg</p>
</div>

MyProject/Areas/Admin/Views/Clients/Details.cshtml
@model MyProject.Models.Client

@{
    ViewBag.Title = "Details";
}

<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-search"></i>  Details
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Summery)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Summery)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PhoneNO)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PhoneNO)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/client/@Model.image" width="100" height="100" />
                    </dd>

                </dl>
                <div class="form-group">
                    <br />
                    <div class="col-md-offset-2 col-md-10">
                        <a href="@Url.Action("Edit", new { id = Model.ClientID })" class="btn btn-sm blue">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                        <a href="@Url.Action("Index")" class="btn btn-sm default">
                            <i class="fa fa-forward"></i> Back to List
                        </a>
                        <br />
                    </div>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/Clients/Edit.cshtml
@model MyProject.Models.Client

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm("Edit", "Clients", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Client</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClientID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summery, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summery, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summery, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="~/Uploads/client/@Model.image" width="100" height="100" />
                <input type="file" id="image" name="image" />

            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyProject/Areas/Admin/Views/Clients/Index.cshtml
@model IEnumerable<MyProject.Models.Client>

@{
    ViewBag.Title = "Index";
}
<div class="col-md-12">

    <a href="@Url.Action("Create")" class="btn  green">
        <i class="fa fa-plus"></i>&nbsp; Create

    </a>

    <br />
    <!-- BEGIN BORDERED TABLE PORTLET-->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-list"></i>Client
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>

            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Summery)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNO)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.image)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Summery)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNO)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                <img src="~/Uploads/Client/@item.image" width="100" height="100" />
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", new { id = item.ClientID })" class="btn btn-sm blue">
                                    Edit <i class="fa fa-edit"></i>
                                </a>
                                <a href="@Url.Action("Details", new { id = item.ClientID })" class="btn btn-sm default">
                                    Details <i class="fa fa-search"></i>
                                </a>
                                <a href="@Url.Action("Delete",new { id = item.ClientID})"
                                   class="btn btn-sm red" id="btnShow">
                                    Delete <i class="fa fa-trash-o"></i>


                                </a>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>

    <!-- END BORDERED TABLE PORTLET-->
</div>