MyProject/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string Image { get; set; }
        public System.DateTime PublishDate { get; set; }
        public bool IsActive { get; set; }
        public int CategoryID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Categotire Categotire { get; set; }
        public virtual Employee Employee { get; set; }
    }
}

MyProject/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;
using PagedList;

namespace MyProject.Areas.Admin.Controllers
{
    
    public class NewsController : Controller
    {
        
        private JobStepEntities db = new JobStepEntities();
        // GET: Admin/News
        public ActionResult Index(string searchBy, string search, int? page)
        {
            var data = db.News.Include(n => n.Employee).Include(n => n.Categotire).OrderByDescending(x => x.PublishDate).AsQueryable();
            if (searchBy == "Title")
            {
                data = data.Where(x => x.Title.Contains(search));
            }
            if (searchBy == "Categotire")
            {
                data = data.Where(x => x.Categotire.Name.Contains(search));
            }
           
            var model = data.ToList().ToPagedList(page ?? 1, 5);
            return View(model);


            //var news = db.News.Include(n => n.Employee).Include(n => n.Categotire);
            //return View(news.ToList());
        }

        // GET: Admin/News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }
        // GET: Admin/News/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "Name");
            ViewBag.CategoryID = new SelectList(db.Categotires, "CategoreyID", "Name");
            return View();
        }

        // POST: Admin/News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(
            [Bind(Include = "NewsID,Title,Details,IsActive,CategoryID,EmployeeID,Image")] News news, HttpPostedFileBase Image)
        {
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "Name", news.EmployeeID);
            ViewBag.CategoryID = new SelectList(db.Categotires, "CategoreyID", "Name", news.CategoryID);

            string guid = Guid.NewGuid().ToString("N").ToLower();
            string Extenstion = Image.FileName.Split('.')[1];
            if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
            {
                return View(news);
            }
            string filename = guid + '.' + Extenstion;
            Image.SaveAs(Server.MapPath("~/Uploads/" + filename));
            news.Image = filename;
            news.PublishDate = DateTime.Now;

            //  ModelState[0].Errors[0].ErrorMessage
            if (ModelState.IsValid)
            {

                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(news);
        }

        // GET: Admin/News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "Name", news.EmployeeID);
            ViewBag.CategoryID = new SelectList(db.Categotires, "CategoreyID", "Name", news.CategoryID);
            return View(news);
        }

        // POST: Admin/News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsID,Title,Details,Image,PublishDate,IsActive,CategoryID,EmployeeID")] News news, HttpPostedFileBase Image)
        {

           
            if (Image != null)
            {
                string guid = Guid.NewGuid().ToString("N").ToLower();
                string Extenstion = Image.FileName.Split('.')[1];
                if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
                {
                    return View(news);
                }
                string filename = guid + '.' + Extenstion;
                Image.SaveAs(Server.MapPath("~/Uploads/" + filename));
                //delete file from server
                string old_file_name = news.Image;
                var uri = new Uri(Server.MapPath("~/Uploads/" + old_file_name));
                System.IO.File.Delete(uri.LocalPath);
                //add new file to database
                news.Image = filename;

            }
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeID = new SelectList(db.Employees, "EmployeeID", "Name", news.EmployeeID);
            ViewBag.CategoryID = new SelectList(db.Categotires, "CategoreyID", "Name", news.CategoryID);
            return View(news);
        }

        // GET: Admin/News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: Admin/News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            //to catch the photo name
            var photoName = "";
            photoName = news.Image;

            db.News.Remove(news);
            db.SaveChanges();

            //delet the photo
           
            string fullPath = Request.MapPath("~/Uploads/"
            + photoName);

            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
               
            }


            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Areas/Admin/Views/News/Create.cshtml
@model MyProject.Models.News


@{
    ViewBag.Title = "Create";
}

@section scripts

{

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">

}
<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-plus"></i>Add News
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            @using (Html.BeginForm("Create", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {



                @Html.AntiForgeryToken()
                @*@Html.Hidden("publishdate",DateTime.Now)*@
                <div class="form-horizontal">
                    <br />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <textarea id="Details" name="Details"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" id="Image" name="Image" />
                                 </div>
                    </div>

                    <div class="form-group">
                            @Html.LabelFor(model => model.PublishDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PublishDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, "Categotires", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                  

                    <div class="form-group">
                        @Html.LabelFor(model => model.EmployeeID, "Add by", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-primary " type="submit">
                                <i class="fa fa-plus"></i>&nbsp; Create
                            </button>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>
@section scriptFooter
{
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
    <script>
                        $(document).ready(function () {
                            $('#Details').summernote({
                                height: 300

                            });
                        });
    </script>

}

MyProject/Areas/Admin/Views/News/Delete.cshtml
@model MyProject.Models.News

@{
    ViewBag.Title = "Delete";
}
<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trash"></i>  Delete
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            <h3>Are you sure you want to delete this? </h3>
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Employee.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Employee.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Categotire.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Categotire.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Details)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Details)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/@Model.Image" height="100" width="100" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PublishDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PublishDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                   
                </dl>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <br />
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-sm red " type="submit">
                                <i class="fa fa-trash"></i>&nbsp; Delete
                            </button>
                            <a href="@Url.Action("Index")" class="btn btn-sm default">
                                <i class="fa fa-forward"></i> Back to List
                            </a>
                            <br />
                        </div>
                    </div>
                }
                <br />
            </div>
        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/News/Details.cshtml
@model MyProject.Models.News

@{
    ViewBag.Title = "Details";
}



<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-search"></i>  Details
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>


                            <dt>
                                @Html.DisplayNameFor(model => model.Details)
                            </dt>

                            <dd>

                                @Html.Raw(@Model.Details)
                            </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/@Model.Image" width="100" height="100" />
                    </dd>
                            

                            <dt>
                                @Html.DisplayNameFor(model => model.PublishDate)
                            </dt>

                            <dd>
                                @Model.PublishDate.ToShortDateString()
                            @*    @Html.DisplayFor(model => model.PublishDate)*@
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.IsActive)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Categotire.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Categotire.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Employee.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Employee.Name)
                            </dd>

                        </dl>
                    


                <div class="form-group">
                    <br />
                    <div class="col-md-offset-2 col-md-10">
                        <a href="@Url.Action("Edit", new { id = Model.NewsID })" class="btn btn-sm blue">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                        <a href="@Url.Action("Index")" class="btn btn-sm default">
                            <i class="fa fa-forward"></i> Back to List
                        </a>
                        <br />
                    </div>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/News/Edit.cshtml
@model MyProject.Models.News



@{
    ViewBag.Title = "Edit";
}
@section scripts

{

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">

}
<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-pencil"></i>Edit News
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            @using (Html.BeginForm("Edit", "News", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.NewsID)
                    @Html.HiddenFor(model => model.PublishDate)
                    @Html.HiddenFor(model => model.Image)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                          

                            <textarea id="Details" name="Details" >@Model.Details</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img src="~/Uploads/@Model.Image" width="100" height="100" />
                            <input type="file" name="Image" id="Image" />
                             </div>
                    </div>

                    

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, "Categotires", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.EmployeeID, "Add by", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("EmployeeID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EmployeeID, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-primary " type="submit">
                                <i class="fa fa-floppy-o"></i>&nbsp; Save
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scriptFooter
{
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
    <script>
                        $(document).ready(function () {
                            $('#Details').summernote({
                                height: 300

                            });
                        });
    </script>

}

MyProject/Areas/Admin/Views/News/Index.cshtml
@model IPagedList<MyProject.Models.News>
@using PagedList.Mvc;
@using PagedList;

@*@model IEnumerable<MyProject.Models.News>*@

@{
    ViewBag.Title = "All News";
   
}
@*<button type="button" class="btn red"><i class="fa fa-user"></i> Profile</button>*@
<div class="col-md-12">
    <a href="@Url.Action("Create", "News")" class="btn  green">
        <i class="fa fa-plus"></i>&nbsp; Create
        
    </a>
   
    <br />
    <!-- BEGIN BORDERED TABLE PORTLET-->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-list"></i>News
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>

            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-bordered table-hover">
                    <tr>
                       
                        <th>
                            @Html.Label(" Categotire ",new { @style = "font-weight:bold;text-align: center;" })
                            @*@Html.Display("Categotire")*@
                         @*   @Html.DisplayNameFor(model => model.Categotire.Name)*@
                        </th>
                        <th>
                            @Html.Label(" News Title ", new { @style = "font-weight:bold;text-align: center;" })
                           
                           @* @Html.DisplayNameFor(model => model.Title)*@
                        </th>
                        <th>
                            @Html.Label("Details", new { @style = "font-weight:bold;text-align: center;" })
                            @*@Html.DisplayNameFor(model => model.Details)*@
                        </th>
                        <th>
                            @Html.Label("Image", new { @style = "font-weight:bold;text-align: center;" })
                            @*@Html.DisplayNameFor(model => model.Image)*@
                        </th>
                        <th>
                            @Html.Label("Publish Date", new { @style = "font-weight:bold;text-align: center;" })
                            @*@Html.DisplayNameFor(model => model.PublishDate)*@
                        </th>
                        <th>
                            @Html.Label("IsActive", new { @style = "font-weight:bold;text-align: center;" })


                          @*  @Html.DisplayNameFor(model => model.IsActive)*@
                        </th>
                        
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                          
                            <td>
                                @Html.DisplayFor(modelItem => item.Categotire.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                
                                @Html.Raw(item.Details)
                            </td>
                            <td>
                                <img src="~/Uploads/@item.Image" width="100" height="100" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PublishDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                           
                            <td>
                                <a href="@Url.Action("Edit", new { id = item.NewsID })" class="btn btn-sm blue">
                                    Edit <i class="fa fa-edit"></i>
                                </a>
                                <a href="@Url.Action("Details", new { id = item.NewsID })" class="btn btn-sm default">
                                    Details <i class="fa fa-search"></i>
                                </a>
                                <a href="@Url.Action("Delete",new { id = item.NewsID})"
                                   class="btn btn-sm red">
                                    Delete <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                        </tr>
                    }

                </table>

            </div>
        </div>
    </div>
    <!-- END BORDERED TABLE PORTLET-->
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", "News", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayItemSliceAndTotal = true })