MyProject/Models/Advertisment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int AdvertismentID { get; set; }
        public string Title { get; set; }
        public string image { get; set; }
        public string URL { get; set; }
        public Nullable<int> PostionID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime FormDate { get; set; }
        public System.DateTime ToDate { get; set; }
    }
}

MyProject/Areas/Admin/Controllers/AdvertismentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;

namespace MyProject.Areas.Admin.Controllers
{
    public class AdvertismentsController : Controller
    {
        private JobStepEntities db = new JobStepEntities();

        // GET: Admin/Advertisments
        public ActionResult Index()
        {
            return View(db.Advertisments.ToList());
        }

        // GET: Admin/Advertisments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisment advertisment = db.Advertisments.Find(id);
            if (advertisment == null)
            {
                return HttpNotFound();
            }
            return View(advertisment);
        }

        // GET: Admin/Advertisments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Advertisments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdvertismentID,Title,image,URL,PostionID,IsActive,PublishDate,FormDate,ToDate")] Advertisment advertisment,HttpPostedFileBase image)
        {

            string guid = Guid.NewGuid().ToString("N").ToLower();
            string Extenstion = image.FileName.Split('.')[1];
            if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
            {
                return View(advertisment);
            }
            string filename = guid + '.' + Extenstion;
            image.SaveAs(Server.MapPath("~/Uploads/advertisment/" + filename));
            advertisment.image = filename;
            advertisment.PublishDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Advertisments.Add(advertisment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(advertisment);
        }

        // GET: Admin/Advertisments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisment advertisment = db.Advertisments.Find(id);
            if (advertisment == null)
            {
                return HttpNotFound();
            }
            return View(advertisment);
        }

        // POST: Admin/Advertisments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AdvertismentID,Title,image,URL,PostionID,IsActive,PublishDate,FormDate,ToDate")] Advertisment advertisment, HttpPostedFileBase Image)
        {
            if (Image != null)
            {
                string guid = Guid.NewGuid().ToString("N").ToLower();
                string Extenstion = Image.FileName.Split('.')[1];
                if (!(Extenstion == "jpg" || Extenstion == "png" || Extenstion == "gif"))
                {
                    return View(advertisment);
                }
                string filename = guid + '.' + Extenstion;
                Image.SaveAs(Server.MapPath("~/Uploads/advertisment/" + filename));
                //delete file from server
                string old_file_name = advertisment.image;
                var uri = new Uri(Server.MapPath("~/Uploads/advertisment/" + old_file_name));
                System.IO.File.Delete(uri.LocalPath);
                //add new file to database
                advertisment.image = filename;
            }
            if (ModelState.IsValid)
            {
                db.Entry(advertisment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(advertisment);
        }

        // GET: Admin/Advertisments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisment advertisment = db.Advertisments.Find(id);
            if (advertisment == null)
            {
                return HttpNotFound();
            }
            return View(advertisment);
        }

        // POST: Admin/Advertisments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advertisment advertisment = db.Advertisments.Find(id);
            //to catch the photo name
            var photoName = "";
            photoName = advertisment.image;

            db.Advertisments.Remove(advertisment);
            db.SaveChanges();
            //delet the photo

            string fullPath = Request.MapPath("~/Uploads/advertisment/"
            + photoName);

            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);

            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Areas/Admin/Views/Advertisments/Create.cshtml
@model MyProject.Models.Advertisment

@{
    ViewBag.Title = "Create";
}

<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-plus"></i>Create Advertisment
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            @using (Html.BeginForm("Create", "Advertisments", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="file" name="image" id="image" />
                         
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostionID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostionID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PostionID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                 

                    <div class="form-group">
                        @Html.LabelFor(model => model.FormDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="date" name="FormDate" id="FormDate" />
                          
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="date" name="ToDate" id="ToDate" />

                           
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-primary " type="submit">
                                <i class="fa fa-plus"></i>&nbsp; Add
                            </button>
                        </div>
                    </div>
                </div>
            }


        </div>

    </div>
</div>

MyProject/Areas/Admin/Views/Advertisments/Delete.cshtml
@model MyProject.Models.Advertisment

@{
    ViewBag.Title = "Delete";
}

<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-trash"></i>  Delete
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            <h3>Are you sure you want to delete this? </h3>
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/@Model.image" width="100" height="100" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.URL)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.URL)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PostionID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostionID)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PublishDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PublishDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.FormDate)
                    </dt>

                    <dd>
                        @Model.FormDate.ToShortDateString()
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ToDate)
                    </dt>

                    <dd>
                        @Model.ToDate.ToShortDateString()
                    </dd>

                </dl>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <br />
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-sm red " type="submit">
                                <i class="fa fa-trash"></i>&nbsp; Delete
                            </button>
                            <a href="@Url.Action("Index")" class="btn btn-sm default">
                                <i class="fa fa-forward"></i> Back to List
                            </a>
                            <br />
                        </div>
                    </div>
                }
                <br />
            </div>
        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/Advertisments/Details.cshtml
@model MyProject.Models.Advertisment

@{
    ViewBag.Title = "Details";
}


<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-search"></i>  Edit
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            <div>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.image)
                    </dt>

                    <dd>
                        <img src="~/Uploads/@Model.image" width="100" height="100" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.URL)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.URL)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PostionID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostionID)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PublishDate)
                    </dt>

                    <dd>
                        @Model.PublishDate.ToShortDateString()
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.FormDate)
                    </dt>

                    <dd>
                        @Model.FormDate.ToShortDateString()
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ToDate)
                    </dt>

                    <dd>
                        @Model.ToDate.ToShortDateString()
                    </dd>

                </dl>
                <div class="form-group">
                    <br />
                    <div class="col-md-offset-2 col-md-10">
                        <a href="@Url.Action("Edit", new { id = Model.AdvertismentID })" class="btn btn-sm blue">
                            <i class="fa fa-edit"></i> Edit
                        </a>
                        <a href="@Url.Action("Index")" class="btn btn-sm default">
                            <i class="fa fa-forward"></i> Back to List
                        </a>
                        <br />
                    </div>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/Advertisments/Edit.cshtml
@model MyProject.Models.Advertisment

@{
    ViewBag.Title = "Edit";
}

<div class="col-md-12">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-pencil"></i>Edit
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            @using (Html.BeginForm("Edit", "Advertisments", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.AdvertismentID)
                    @Html.HiddenFor(model => model.image)
                    @Html.HiddenFor(model => model.PublishDate)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img src="~/Uploads/advertisment/@Model.image" width="100" height="100" />
                            <input type="file" id="image" name="image" />
                         
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostionID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostionID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PostionID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                 

                    <div class="form-group">
                        @Html.LabelFor(model => model.FormDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FormDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FormDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button class="btn btn-primary " type="submit">
                                <i class="fa fa-floppy-o"></i>&nbsp; Save
                            </button>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>

MyProject/Areas/Admin/Views/Advertisments/Index.cshtml
@model IEnumerable<MyProject.Models.Advertisment>

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12">
    <a href="@Url.Action("Create")" class="btn  green">
        <i class="fa fa-plus"></i>&nbsp; Create

    </a>
    <br />
    <!-- BEGIN BORDERED TABLE PORTLET-->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-list"></i>Advertisment
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>

            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.image)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.URL)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PostionID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PublishDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FormDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ToDate)
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                <img src="~/Uploads/advertisment/@item.image" width="100" height="100" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.URL)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PostionID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PublishDate)
                            </td>
                            <td>
                                @item.FormDate.ToShortDateString()
                                @*@Html.DisplayFor(modelItem => item.FormDate)*@
                            </td>
                            <td>
                                @item.ToDate.ToShortDateString()
                                @*@Html.DisplayFor(modelItem => item.ToDate)*@
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", new { id = item.AdvertismentID })" class="btn btn-sm blue">
                                    Edit <i class="fa fa-edit"></i>
                                </a>
                                <a href="@Url.Action("Details", new { id = item.AdvertismentID })" class="btn btn-sm default">
                                    Details <i class="fa fa-search"></i>
                                </a>
                                <a href="@Url.Action("Delete",new { id = item.AdvertismentID})"
                                   class="btn btn-sm red">
                                    Delete <i class="fa fa-trash-o"></i>
                                </a>

                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
    <!-- END BORDERED TABLE PORTLET-->
</div>